;/*FB_PKG_DELIM*/

__d("CatalogSetsMenuCometQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24196812436623960"}),null);
__d("CatalogSetsMenuCometQuery$Parameters",["CatalogSetsMenuCometQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CatalogSetsMenuCometQuery_facebookRelayOperation"),metadata:{},name:"CatalogSetsMenuCometQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CommerceManagerSetsPageRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25471329129216732"}),null);
__d("CommerceManagerSetsPageRootQuery$Parameters",["CommerceManagerSetsPageRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CommerceManagerSetsPageRootQuery_facebookRelayOperation"),metadata:{},name:"CommerceManagerSetsPageRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("ProductSetOrdering",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum")({NAME_ASC:"name_asc",NAME_DESC:"name_desc",CREATION_TIME_ASC:"creation_time_asc",CREATION_TIME_DESC:"creation_time_desc"}),l=e;i.default=l}),66);
__d("ProductSetUsageType",[],(function(t,n,r,o,a,i){var e=Object.freeze({SHOPS:"shops",IG_DROPS:"ig_drops",IG_SELLER_CURATED:"ig_seller_curated",AUGMENTED_REALITY_COMMERCE:"augmented_reality_commerce",DA:"da",DA_CREATIVE:"da_creative",LIVE_SHOPPING:"live_shopping",MINI_SHOPS:"mini_shops",SHOPS_ADDED_ITEMS:"shops_added_items",PRODUCT_DISCOUNT:"product_discount",PRODUCT_DISCOUNT_PREREQUISITE:"product_discount_prerequisite",DIGITAL_CIRCULAR:"digital_circular",DAPL:"dapl",CATALOG_COLLECTION:"catalog_collection",SHIPPING_SIGNAL:"shipping_signal",IG_TAGGING:"ig_tagging",FB_TAGGING:"fb_tagging",MARKETPLACE_SHOPS:"marketplace_shops",MULTI_PHOTO_AD_POST:"multi_photo_ad_post",MINI_SHOPS_STOREFRONT:"mini_shop_storefront",CATALOG_SEGMENT_BACKED_PRODUCT_SET:"cpas_segment_backed_product_set",SHOP_COLLECTION_AD:"shop_collection_ad",SHOP_COLLECTION_PAGE:"shop_collection_page",SHOP_COLLECTION_PAGE_DRAFT:"shop_collection_page_draft",SHOP_COLLECTION_AUTO_CREATION_CANDIDATE:"shop_collection_auto_creation_candidate",SHOP_FEATURED_ITEMS:"shops_featured_items",SHOP_SIGNAL_NODE:"shop_signal_platform",SHOP_NAVIGATION_BASIC_NODE:"shop_navigation",SHOP_PDP_STORYTELLING:"shop_pdp_storytelling",SHOP_SMART_COLLECTION:"shop_smart_collection",WHATSAPP_CATALOG:"whatsapp_catalog",AFFILIATE_CAMPAIGN:"affiliate_campaign",TEST_DYNAMIC_DO_NOT_USE:"test_dynamic_do_not_use",FB_DISCOUNT_OPT_OUT:"fb_discount_opt_out",ACTIVE_STATIC_ADS_FOR_PRODUCT_SET_ONSITE_DESTINATION:"active_static_ads_for_product_set_onsite_destination",AMAZON_BUY_WITH_PRIME:"amazon",WALMART_INTEGRATED_CHECKOUT:"walmart",SHOPEE_INTEGRATED_CHECKOUT:"shopee",MELI_INTEGRATED_CHECKOUT:"meli",ZALANDO_INTEGRATED_CHECKOUT:"zalando",SHEIN_INTEGRATED_CHECKOUT:"shein",LOWES_INTEGRATED_CHECKOUT:"lowes",PARTNER_INTEGRATION_PLATFORM:"partner_integration_platform",BIZ_AI_BEST_SELLER:"biz_ai_best_seller",AI_PRODUCT_RECOMMENDATIONS:"ai_product_recommendations",BUDGET_SPLIT_ADS:"budget_split_ads",GENAI_CREATIVE_FEATURE_SETTINGS:"genai_creative_feature_settings",SITE_EXTENSION_ADS:"site_extensions_ads",OPTIMIZED_MULTI_POST_AD:"optimized_multi_post_ad",CREATIVE_SINGLE_IMAGE_TEMPLATE_AD:"creative_single_image_template_ad",DA_ADOPTION_FROM_SINGLE_MEDIA:"da_adoption_from_single_media"});i.default=e}),66);
__d("ProductSetIssueType",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum").Mirrored(["ADS_PAUSED_DUE_TO_INSUFFICIENT_ELIGIBLE_ITEMS"]),l=e;i.default=l}),66);
__d("XFBProductSetIssueTypeUtils.facebook",["$InternalEnumUtils","ProductSetIssueType"],(function(t,n,r,o,a,i,l){var e=o("$InternalEnumUtils").createToJSEnum(r("ProductSetIssueType")),s=o("$InternalEnumUtils").createFromJSEnum(r("ProductSetIssueType"));l.toJSEnum=e,l.fromJSEnum=s}),98);
__d("XFBProductSetOrderingUtils.facebook",["$InternalEnumUtils","ProductSetOrdering"],(function(t,n,r,o,a,i,l){var e=o("$InternalEnumUtils").createToJSEnum(r("ProductSetOrdering")),s=o("$InternalEnumUtils").createFromJSEnum(r("ProductSetOrdering"));l.toJSEnum=e,l.fromJSEnum=s}),98);
__d("getCatalogSetsMenuIssueTypeFilters.entrypointutils",["isStringNotNullAndNotWhitespaceOnly"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return r("isStringNotNullAndNotWhitespaceOnly")(e)?JSON.parse(e):[]}l.default=e}),98);
__d("getCatalogSetsMenuUsageTypeFilters",["isStringNotNullAndNotWhitespaceOnly"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return r("isStringNotNullAndNotWhitespaceOnly")(e)?JSON.parse(e):[]}l.default=e}),98);
__d("getCatalogSetsMenuCometQueryVariables",["ProductSetOrdering","ProductSetUsageType","XFBProductSetIssueTypeUtils.facebook","XFBProductSetOrderingUtils.facebook","filterNulls","getCatalogSetsMenuIssueTypeFilters.entrypointutils","getCatalogSetsMenuUsageTypeFilters","getGraphQLEnumSafe"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t,n=e.areVariantsEnabled,a=e.catalogID,i=e.searchText,l=e.selectedProductSetIssueTypes,s=e.selectedProductSetUsages,u=e.sort;return{areVariantsEnabled:n,catalogID:a,issueTypes:r("filterNulls")(r("getCatalogSetsMenuIssueTypeFilters.entrypointutils")(l).map(function(e){return o("XFBProductSetIssueTypeUtils.facebook").fromJSEnum(e)})),nameFilter:i,sort:r("filterNulls")([o("XFBProductSetOrderingUtils.facebook").fromJSEnum((t=r("ProductSetOrdering").cast(u))!=null?t:"name_asc")]),usageTypeFilter:r("filterNulls")(r("getCatalogSetsMenuUsageTypeFilters")(s).map(function(e){return r("getGraphQLEnumSafe")(r("ProductSetUsageType"),e)}))}}l.default=e}),98);
__d("CommerceManagerSetsPageRoot.entrypoint",["CatalogSetsMenuCometQuery$Parameters","CommerceManagerCatalogItemsDetailCardContainer.entrypoint","CommerceManagerSetsPageRootQuery$Parameters","JSResourceForInteraction","NestedRelayEntryPointBuilderUtils","buildCommerceManagerWithSidebarNavigation.entrypoint","getCatalogSetsMenuCometQueryVariables"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(r("JSResourceForInteraction")("CommerceManagerSetsPageRoot.react").__setRef("CommerceManagerSetsPageRoot.entrypoint"),function(e){var t,a;return{entryPoints:{itemPDP:e.routeParams.showItemPDPForItemID!==null?o("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:n("CommerceManagerCatalogItemsDetailCardContainer.entrypoint"),entryPointParams:{cardQuery:{activeRowID:(t=e.routeParams.showItemPDPForItemID)!=null?t:"",catalogID:e.routeParams.catalog_id,selectedVersionFilter:e.routeParams.versionFilter}}}):null},queries:{CatalogSetsMenuCometQueryReference:{parameters:r("CatalogSetsMenuCometQuery$Parameters"),variables:r("getCatalogSetsMenuCometQueryVariables")({areVariantsEnabled:e.routeProps.are_variants_enabled,catalogID:e.routeParams.catalog_id,searchText:e==null||(a=e.passthroughProps)==null?void 0:a.setsListSearchText,selectedProductSetIssueTypes:e.routeParams.issueTypes,selectedProductSetUsages:e.routeParams.filter_by_usages,sort:e.routeParams.sets_list_sort})},CommerceManagerSetsPageRootQueryReference:{parameters:r("CommerceManagerSetsPageRootQuery$Parameters"),variables:{catalogID:e.routeParams.catalog_id}}}}});l.default=e}),98);