;/*FB_PKG_DELIM*/

__d("BizNotificationTogglePreferencesModeAction",["BizNotificationPopoverDataProvider","BizNotificationTogglePreferencesModeReducerPlugin","Laminar"],(function(t,n,r,o,a,i){"use strict";var e=n("Laminar").__createAction(function(){return[n("Laminar").__createReducer(n("BizNotificationTogglePreferencesModeReducerPlugin"),n("BizNotificationPopoverDataProvider"),{},"")]},function(){return[]},"BIZ_NOTIFICATION.TOGGLE_PREFERENCES_MODE");a.exports=e}),null);/*FB_PKG_DELIM*/
__d("BizNotificationToggleUnreadsOnlyAction",["BizNotificationPopoverDataProvider","BizNotificationToggleUnreadsOnlyReducerPlugin","Laminar"],(function(t,n,r,o,a,i){"use strict";var e=n("Laminar").__createAction(function(){return[n("Laminar").__createReducer(n("BizNotificationToggleUnreadsOnlyReducerPlugin"),n("BizNotificationPopoverDataProvider"),{},"")]},function(){return[]},"BIZ_NOTIFICATION.TOGGLE_UNREADS_ONLY");a.exports=e}),null);/*FB_PKG_DELIM*/
__d("AdsMgmt2025H2JewelScopeSelectorExperimentUtils",["AdsMgmtJewelExperimentUtils","qex"],(function(t,n,r,o,a,i,l){"use strict";function e(){return o("AdsMgmtJewelExperimentUtils").getIsUserInAMDPage()&&u(!0)}function s(){return o("AdsMgmtJewelExperimentUtils").getIsUserInAMDPage()&&u(!1)}function u(e){return e?r("qex")._("1608")===!0:r("qex")._("1624")===!0}l.getUserShouldSeeJewelScopeSelectorWithExposure=e,l.getUserShouldSeeJewelScopeSelectorNoExposure=s}),98);/*FB_PKG_DELIM*/
__d("AdsMgmtJewelExperimentUtils",["URI"],(function(t,n,r,o,a,i,l){"use strict";var e,s=["/adsmanager","/billing_hub","/events_manager2"];function u(){var t=(e||(e=r("URI"))).getRequestURI().getPath();return s.some(function(e){return t.startsWith(e)})}l.getIsUserInAMDPage=u}),98);/*FB_PKG_DELIM*/
__d("AdsMgmt2025H1JewelRevampExperimentUtils",["AdsMgmtJewelExperimentUtils","gkx"],(function(t,n,r,o,a,i,l){"use strict";function e(){if(!o("AdsMgmtJewelExperimentUtils").getIsUserInAMDPage())return!1;var e=s();return!e}function s(){return r("gkx")("19885")}l.getUserShouldSeeJewelInGeo2=e}),98);/*FB_PKG_DELIM*/
__d("BizNotificationTogglePreferencesModeReducerPlugin",[],(function(t,n,r,o,a,i){"use strict";var e={reduce:function(t,n){return babelHelpers.extends({},t,{isPreferencesMode:n.isPreferencesMode})}},l=e;i.default=l}),66);/*FB_PKG_DELIM*/
__d("BizNotificationToggleUnreadsOnlyReducerPlugin",[],(function(t,n,r,o,a,i){"use strict";var e={reduce:function(t,n){return babelHelpers.extends({},t,{showUnreadsOnly:n.showUnreadsOnly})}},l=e;i.default=l}),66);/*FB_PKG_DELIM*/
__d("BizNotificationPopoverDataProvider",["BizNotificationPopoverDataProviderPlugin","Laminar"],(function(t,n,r,o,a,i){"use strict";a.exports=n("Laminar").__createProvider(n("BizNotificationPopoverDataProviderPlugin"),"BizNotificationPopoverDataProviderPlugin")}),null);