;/*FB_PKG_DELIM*/

__d("CommerceManagerDataSourcesPageRootQuery$Parameters",["CommerceManagerDataSourcesPageRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CommerceManagerDataSourcesPageRootQuery_facebookRelayOperation"),metadata:{},name:"CommerceManagerDataSourcesPageRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CommerceManagerDataSourcesPageRoot.entrypoint",["CommerceManagerDataSourcesPageRootQuery$Parameters","JSResourceForInteraction","buildCommerceManagerWithSidebarNavigation.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(r("JSResourceForInteraction")("CommerceManagerDataSourcesPageRoot.react").__setRef("CommerceManagerDataSourcesPageRoot.entrypoint"),function(e){return{queries:{CommerceManagerDataSourcesPageRootQueryReference:{parameters:r("CommerceManagerDataSourcesPageRootQuery$Parameters"),variables:{catalogID:e.routeParams.catalog_id}}}}});l.default=e}),98);
__d("CommerceManagerDataSourcesV2PageRootQuery$Parameters",["CommerceManagerDataSourcesV2PageRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CommerceManagerDataSourcesV2PageRootQuery_facebookRelayOperation"),metadata:{},name:"CommerceManagerDataSourcesV2PageRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CommerceManagerDataSourcesV2PageRoot.entrypoint",["CommerceManagerDataSourcesV2PageRootQuery$Parameters","JSResourceForInteraction","buildCommerceManagerWithSidebarNavigation.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(r("JSResourceForInteraction")("CommerceManagerDataSourcesV2PageRoot.react").__setRef("CommerceManagerDataSourcesV2PageRoot.entrypoint"),function(e){return{queries:{CommerceManagerDataSourcesV2PageRootQueryReference:{parameters:r("CommerceManagerDataSourcesV2PageRootQuery$Parameters"),variables:{catalogID:e.routeParams.catalog_id,filterByType:e.routeParams.filter_by_type,partner:"SHOPIFY",searchQuery:e.routeParams.search_query,sortDirection:e.routeParams.sort_direction,sortKey:e.routeParams.sort_key,versionID:e.routeParams.version_id}}}}});l.default=e}),98);
__d("CommerceManagerEventsPageRootQuery$Parameters",["CommerceManagerEventsPageRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CommerceManagerEventsPageRootQuery_facebookRelayOperation"),metadata:{},name:"CommerceManagerEventsPageRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CommerceManagerEventsPageRoot.entrypoint",["CommerceManagerEventsPageRootQuery$Parameters","JSResourceForInteraction","buildCommerceManagerWithSidebarNavigation.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(r("JSResourceForInteraction")("CommerceManagerEventsPageRoot.react").__setRef("CommerceManagerEventsPageRoot.entrypoint"),function(e){return{queries:{CommerceManagerEventsPageRootQueryReference:{parameters:r("CommerceManagerEventsPageRootQuery$Parameters"),variables:{catalogID:e.routeParams.catalog_id}}}}});l.default=e}),98);
__d("CommerceManagerOverviewPageRootQuery$Parameters",["CommerceManagerOverviewPageRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CommerceManagerOverviewPageRootQuery_facebookRelayOperation"),metadata:{},name:"CommerceManagerOverviewPageRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CommerceManagerOverviewPageRoot.entrypoint",["CommerceManagerOverviewPageRootQuery$Parameters","JSResourceForInteraction","buildCommerceManagerWithSidebarNavigation.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(r("JSResourceForInteraction")("CommerceManagerOverviewPageRoot.react").__setRef("CommerceManagerOverviewPageRoot.entrypoint"),function(e){return{extraProps:{catalogID:e.routeProps.catalog_id,cmsID:e.routeProps.cms_id},queries:{CommerceManagerOverviewPageRootQueryReference:{parameters:r("CommerceManagerOverviewPageRootQuery$Parameters"),variables:{catalogID:e.routeProps.catalog_id}}}}});l.default=e}),98);