;/*FB_PKG_DELIM*/

__d("CommerceManagerWithSettingsPageLayoutRootQuery$Parameters",["CommerceManagerWithSettingsPageLayoutRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CommerceManagerWithSettingsPageLayoutRootQuery_facebookRelayOperation"),metadata:{},name:"CommerceManagerWithSettingsPageLayoutRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("buildCommerceManagerWithSettingsPageLayout.entrypoint",["CommerceManagerWithSettingsPageLayoutRootQuery$Parameters","JSResourceForInteraction","createContentAreaCompoundEntryPointBuilder"],(function(t,n,r,o,a,i,l){"use strict";var e=r("createContentAreaCompoundEntryPointBuilder")(r("JSResourceForInteraction")("CommerceManagerWithSettingsPageLayoutRoot.react").__setRef("buildCommerceManagerWithSettingsPageLayout.entrypoint"),function(e){var t=e.routeParams.catalog_or_cms_id;return{sidebarQueryReference:{parameters:n("CommerceManagerWithSettingsPageLayoutRootQuery$Parameters"),variables:{catalogOrCmsID:t,cmsID:e.routeProps.cms_id,hasCmsID:e.routeProps.cms_id!=null}}}});l.default=e}),98);
__d("CommerceManagerSettingsAssetsPageRoot.entrypoint",["JSResourceForInteraction","buildCommerceManagerWithSettingsPageLayout.entrypoint","buildCommerceManagerWithSidebarNavigation.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{entryPoints:{},queries:{}}},root:r("JSResourceForInteraction")("CommerceManagerSettingsAssetsPageRoot.react").__setRef("CommerceManagerSettingsAssetsPageRoot.entrypoint")},s=r("buildCommerceManagerWithSettingsPageLayout.entrypoint")(e.root,e.getPreloadProps),u=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(s.root,s.getPreloadProps);l.default=u}),98);
__d("CommerceManagerSettingsCatalogPageRoot.entrypoint",["JSResourceForInteraction","buildCommerceManagerWithSettingsPageLayout.entrypoint","buildCommerceManagerWithSidebarNavigation.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{entryPoints:{},queries:{}}},root:r("JSResourceForInteraction")("CommerceManagerSettingsCatalogPageRoot.react").__setRef("CommerceManagerSettingsCatalogPageRoot.entrypoint")},s=r("buildCommerceManagerWithSettingsPageLayout.entrypoint")(e.root,e.getPreloadProps),u=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(s.root,s.getPreloadProps);l.default=u}),98);
__d("CommerceManagerSettingsGeneralPageRootQuery$Parameters",["CommerceEmailOptInGetSubscriberListButton.relayprovider","CommerceManagerSettingsGeneralPageRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CommerceManagerSettingsGeneralPageRootQuery_facebookRelayOperation"),metadata:{},name:"CommerceManagerSettingsGeneralPageRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__CommerceEmailOptInGetSubscriberListButtonrelayprovider:n("CommerceEmailOptInGetSubscriberListButton.relayprovider")}}};a.exports=e}),null);
__d("CommerceManagerSettingsGeneralPageRoot.entrypoint",["CommerceManagerSettingsGeneralPageRootQuery$Parameters","JSResourceForInteraction","buildCommerceManagerWithSettingsPageLayout.entrypoint","buildCommerceManagerWithSidebarNavigation.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.routeParams.catalog_or_cms_id;return{entryPoints:{},queries:{root:{parameters:r("CommerceManagerSettingsGeneralPageRootQuery$Parameters"),variables:{catalog_or_cms_id:e}}}}},root:r("JSResourceForInteraction")("CommerceManagerSettingsGeneralPageRoot.react").__setRef("CommerceManagerSettingsGeneralPageRoot.entrypoint")},s=r("buildCommerceManagerWithSettingsPageLayout.entrypoint")(e.root,e.getPreloadProps),u=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(s.root,s.getPreloadProps);l.default=u}),98);
__d("CommerceManagerShopsUpsellPageRootQuery$Parameters",["CommerceManagerShopsUpsellPageRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CommerceManagerShopsUpsellPageRootQuery_facebookRelayOperation"),metadata:{},name:"CommerceManagerShopsUpsellPageRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CommerceManagerShopsUpsellPageRoot.entrypoint",["CommerceManagerShopsUpsellPageRootQuery$Parameters","JSResourceForInteraction","buildCommerceManagerWithSidebarNavigation.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCommerceManagerWithSidebarNavigation.entrypoint")(r("JSResourceForInteraction")("CommerceManagerShopsUpsellPageRoot.react").__setRef("CommerceManagerShopsUpsellPageRoot.entrypoint"),function(e){return{queries:{CommerceManagerShopsUpsellPageRootQueryReference:{parameters:r("CommerceManagerShopsUpsellPageRootQuery$Parameters"),variables:{catalogID:e.routeParams.catalog_id}}}}});l.default=e}),98);